// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table user {
  _id ObjectId [primary key]
  username string
  password_hash string
  email string 
  name_first string
  name_last string
  email_verified boolean
  email_verification_code string
}

Table deck {
  _id ObjectId [primary key]
  id_user ObjectId
  name string
}

Table card {
  _id ObjectId [primary key]
  id_deck ObjectId
  side_front string
  side_back string
  card_shown boolean
}

Ref: deck.id_user > user._id // many-to-one

Ref: card.id_deck > deck._id